# Generated by Django 3.2.16 on 2023-05-01 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0002_auto_20230501_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inviter',
            fields=[
                ('inviter_id', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(max_length=50)),
                ('meeting_details', models.CharField(blank=True, max_length=250, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('is_booked', models.BooleanField()),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inviter.inviter')),
            ],
        ),
    ]
