# Generated by Django 3.2.16 on 2023-09-10 15:26

from django.db import migrations, models
import django.db.models.deletion
import inviter.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20230501_1228'),
        ('inviter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inviter',
            name='email_sender_creds',
            field=models.ForeignKey(default=inviter.models.get_default_creds_pk, on_delete=django.db.models.deletion.SET_DEFAULT, to='event.oauthcredentials'),
        ),
    ]
