# Generated by Django 3.2.16 on 2023-05-01 04:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateRange',
            fields=[
                ('date_range_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='OauthCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=256)),
                ('refresh_token', models.CharField(max_length=256)),
                ('token_uri', models.CharField(max_length=256)),
                ('client_id', models.CharField(max_length=256)),
                ('client_secret', models.CharField(max_length=256)),
            ],
        ),
        migrations.RenameField(
            model_name='event',
            old_name='id',
            new_name='event_id',
        ),
        migrations.AddField(
            model_name='event',
            name='counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.IntegerField(default=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2023, 5, 1, 4, 28, 24, 997795, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='share_id',
            field=models.CharField(default=123, max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2023, 5, 1, 4, 28, 41, 790277, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['share_id'], name='event_event_share_i_db4692_idx'),
        ),
        migrations.AddField(
            model_name='daterange',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
    ]
